import Link from 'next/link';
import {groupedRoutes,platformRoutes} from '../lib/routes';
import {CONTROL_GATES,TASK_STATES} from '../lib/operations';

const implemented=platformRoutes.filter(route=>route.status==='implemented').length;
const controlled=platformRoutes.filter(route=>route.status==='controlled').length;
const externalGate=platformRoutes.filter(route=>route.status==='external-gate').length;
const protectedRoutes=platformRoutes.filter(route=>route.access!=='public').length;

const executiveMetrics=[
 {value:'24',label:'Governed application surfaces',detail:'Public, authenticated, restricted, and external-gated workspaces'},
 {value:'15',label:'Mandatory control gates',detail:'From intake and identity through acknowledgment and retention'},
 {value:'16',label:'Task and exception states',detail:'Operational state discipline for every case and service order'},
 {value:'8',label:'Event automation triggers',detail:'Intake, documents, signatures, acknowledgments, notices, payments, refunds, and security'}
];

const platformLanes=[
 {number:'01',title:'Client Experience',text:'Secure intake, questionnaires, document exchange, signatures, payments, notices, timeline visibility, and delivery acknowledgment.',href:'/client-portal',items:['Identity-aware onboarding','Missing-document requests','Case status narratives','Secure final delivery']},
 {number:'02',title:'Practitioner Production',text:'Preparation workpapers, due diligence, reviewer disposition, pricing approvals, engagement controls, signatures, and exception routing.',href:'/practitioner-work-zone',items:['Return workflow controls','Reviewer and override gates','Authority and consent records','Immutable evidence lineage']},
 {number:'03',title:'ERO and E-file Operations',text:'Submission intent, schema readiness, environment isolation, idempotency, acknowledgments, rejects, retries, and transmission evidence.',href:'/efile-workbench',items:['ATS and production separation','Duplicate transmission protection','Acknowledgment correlation','Fail-closed external adapter']},
 {number:'04',title:'Intelligence and Resolution',text:'Refund evidence, transcript reconciliation, notice classification, service queues, analytics, and policy-scoped AI assistance.',href:'/refund-intelligence',items:['Refund lane confidence','Masterfile variance scoring','Notice deadline workflow','Human-reviewed AI tasks']}
];

const lifecycle=[
 ['Intake','Identity, conflict, engagement, consent, scope, pricing, and evidence collection'],
 ['Prepare','Document classification, workpapers, due diligence, calculations, and issue detection'],
 ['Review','Independent quality review, exception handling, approval, and material-action controls'],
 ['Authorize','Client approval, signatures, identity confirmation, and transmission readiness'],
 ['Transmit','Environment-isolated submission intent, idempotency, adapter gate, and worker dispatch'],
 ['Resolve','Acknowledgments, rejects, notices, refund evidence, escalation, delivery, and retention']
];

const assurances=[
 {title:'Multi-tenant security',text:'Tenant, office, user, role, client, and case scopes remain explicit at every protected operation.'},
 {title:'Evidence-first architecture',text:'Material actions produce correlation identifiers, decision records, disposition evidence, and retention-ready audit events.'},
 {title:'Human accountability',text:'AI and automation assist the workforce but cannot sign, represent, transmit, alter banking data, or clear material holds.'},
 {title:'Production certification',text:'Application availability is separated from production readiness through a fail-closed readiness endpoint and release evidence gates.'}
];

export default function HomePage(){
 return <>
  <section className="executive-hero"><div className="container executive-hero__grid">
   <div className="executive-hero__copy"><div className="product-kicker"><span>ROSS TAX PRO SOFTWARE CO.</span><b>RTPSC OPERATIONS FABRIC</b></div><h1>The enterprise operating system for modern tax practices.</h1><p className="lead">A premium, governed platform for taxpayers, preparers, reviewers, EROs, administrators, payroll teams, compliance officers, educators, and multi-office firms—engineered to control the full lifecycle rather than merely enter a return.</p><div className="actions"><Link className="ross-btn ross-btn--gold executive-primary" href="/start">Launch Secure Intake</Link><Link className="ross-btn ross-btn--outline executive-secondary" href="/operations-fabric">Explore the Platform</Link></div><div className="trust-row"><span>Multi-tenant</span><span>MFA + RBAC</span><span>Evidence lineage</span><span>Fail-closed adapters</span><span>Human review gates</span></div></div>
   <aside className="executive-console" aria-label="Executive platform preview"><div className="executive-console__top"><div><span className="console-kicker">Executive Operations</span><h2>Firm Command Overview</h2></div><span className="live-chip"><i/>Application online</span></div><div className="console-metrics"><article><small>Open workflow lanes</small><strong>06</strong><span>Intake through retention</span></article><article><small>Governed routes</small><strong>{platformRoutes.length}</strong><span>{protectedRoutes} protected surfaces</span></article><article><small>Control gates</small><strong>{CONTROL_GATES.length}</strong><span>PASS · FLAG · HOLD · DENY</span></article><article><small>Task states</small><strong>{TASK_STATES.length}</strong><span>Normal and exception paths</span></article></div><div className="console-queue"><div className="console-queue__head"><b>Priority workstreams</b><span>Role-scoped</span></div>{[['Client intake','Identity and engagement'],['Return production','Preparation and review'],['E-file control','Approval and acknowledgment'],['Resolution','Notices and refund evidence']].map(([name,state],index)=><div className="queue-line" key={name}><span className="queue-index">0{index+1}</span><div><b>{name}</b><small>{state}</small></div><em>{index===0?'READY':index===1?'ACTIVE':index===2?'GATED':'MONITORED'}</em></div>)}</div><div className="console-footer"><Link href="/api/health">Health</Link><Link href="/api/platform/status">Runtime</Link><Link href="/api/ready">Readiness</Link></div></aside>
  </div></section>

  <section className="executive-metric-band"><div className="container executive-metric-grid">{executiveMetrics.map(metric=><article key={metric.label}><strong>{metric.value}</strong><div><b>{metric.label}</b><span>{metric.detail}</span></div></article>)}</div></section>

  <section className="section corporate-intro"><div className="container"><div className="corporate-heading"><div><div className="eyebrow">One Platform · Every Operating Role</div><h2>Designed as a complete practice infrastructure—not a collection of disconnected tax screens.</h2></div><p>RTPSC organizes every material event around identity, authority, evidence, workflow state, human accountability, exception handling, and release discipline. The result is a unified operating model for client service, tax production, e-file, notices, payroll, analytics, compliance, and growth.</p></div><div className="platform-lane-grid">{platformLanes.map(lane=><article className="platform-lane" key={lane.number}><span className="platform-lane__number">{lane.number}</span><h3>{lane.title}</h3><p>{lane.text}</p><ul>{lane.items.map(item=><li key={item}>{item}</li>)}</ul><Link href={lane.href}>Enter {lane.title} →</Link></article>)}</div></div></section>

  <section className="section experience-section"><div className="container experience-grid"><div><div className="eyebrow">Premium User Experience</div><h2>Purpose-built interfaces for every participant in the tax ecosystem.</h2><p>Each role receives a dedicated workspace with the information density, controls, actions, terminology, and evidence required for its responsibilities—without exposing unrelated taxpayer data or privileged functions.</p><div className="persona-tabs"><span>Taxpayer</span><span>Preparer</span><span>Reviewer</span><span>ERO</span><span>Administrator</span><span>Compliance</span></div></div><div className="interface-stack"><article className="interface-panel interface-panel--primary"><header><span>Practitioner Workspace</span><em>Restricted</em></header><div className="interface-panel__body"><aside><b>Client</b><b>Documents</b><b>Workpapers</b><b>Review</b><b>Signatures</b><b>E-file</b></aside><main><div className="ui-title"><div><small>2026 Individual Return</small><strong>Preparation and Review</strong></div><span>IN PROGRESS</span></div><div className="ui-progress"><i/><i/><i/><i/><i/><i/></div><div className="ui-cards"><div><small>Documents</small><b>18 received</b><span>2 items requested</span></div><div><small>Due diligence</small><b>Review required</b><span>1 flagged response</span></div><div><small>Approval</small><b>Not released</b><span>Reviewer disposition pending</span></div></div></main></div></article><article className="interface-panel interface-panel--floating"><header><span>Client Timeline</span><em>Authenticated</em></header><div className="timeline-mini"><i/><div><b>Documents received</b><small>Evidence preserved and classified</small></div><i/><div><b>Preparation underway</b><small>Missing-item request delivered</small></div><i/><div><b>Review pending</b><small>No delivery date promised</small></div></div></article></div></div></section>

  <section className="section lifecycle-section"><div className="container"><div className="section-heading"><div><div className="eyebrow">End-to-End Tax Lifecycle</div><h2>A disciplined operating sequence from first contact through retention.</h2></div><p>Every lifecycle phase carries its own authorization requirements, required evidence, automated triggers, human checkpoints, failure states, and audit outcomes.</p></div><div className="lifecycle-premium">{lifecycle.map(([title,text],index)=><article key={title}><span>{String(index+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></div></section>

  <section className="section intelligence-suite"><div className="container intelligence-grid"><div className="intelligence-copy"><div className="eyebrow">ETRAC Intelligence Suite</div><h2>Transform verified events into controlled next actions.</h2><p>ETRAC correlates intake, documents, signatures, acknowledgments, authorized transcript observations, notices, refund evidence, payments, and security anomalies. Each event creates a governed task path instead of an unstructured message or guess.</p><div className="intelligence-actions"><Link href="/analytics">Operational analytics</Link><Link href="/refund-intelligence">Refund intelligence</Link><Link href="/masterfile-reconciliation">Reconciliation suite</Link><Link href="/ai-workforce">AI workforce governance</Link></div></div><div className="intelligence-board"><header><b>Event Intelligence Board</b><span>Evidence linked</span></header>{[['ACK_RECEIVED','Correlate acknowledgment','PASS'],['NOTICE_UPLOADED','Classify and assign response','REVIEW'],['REFUND_EVIDENCE_ADDED','Infer lane and confidence','MONITOR'],['SECURITY_ANOMALY','Suspend material action','HOLD']].map(([event,action,status])=><div className="intelligence-row" key={event}><code>{event}</code><span>{action}</span><em data-status={status}>{status}</em></div>)}</div></div></section>

  <section className="section assurance-section"><div className="container"><div className="section-heading"><div><div className="eyebrow">Corporate Assurance</div><h2>Security, governance, and release discipline are part of the product—not an afterthought.</h2></div><p>The platform distinguishes implemented software, configured infrastructure, authorized external adapters, and production certification. That separation prevents polished screens from overstating operational readiness.</p></div><div className="assurance-grid">{assurances.map((item,index)=><article key={item.title}><span>0{index+1}</span><h3>{item.title}</h3><p>{item.text}</p></article>)}</div><div className="assurance-bar"><div><b>Application status</b><span>Implemented and validated</span></div><div><b>Production status</b><span>Certified only when `/api/ready` returns 200</span></div><div><b>External systems</b><span>Fail closed until separately authorized</span></div></div></div></section>

  <section className="section directory-preview" id="platform-directory"><div className="container"><div className="section-heading"><div><div className="eyebrow">Complete Platform Index</div><h2>Every module, workflow, interface, and system boundary in one governed directory.</h2></div><p><b>Implemented</b> identifies active application surfaces. <b>Controlled</b> requires authenticated role and policy enforcement. <b>External gate</b> remains unable to contact outside systems until authorization evidence is complete.</p></div><div className="status-strip"><span>{implemented} implemented</span><span>{controlled} controlled</span><span>{externalGate} external-gate</span><span>{protectedRoutes} protected</span></div>{Object.entries(groupedRoutes).map(([category,routes])=>routes.length>0&&<section className="route-group" key={category}><div className="route-group__heading"><h3>{category}</h3><span>{routes.length} modules</span></div><div className="route-grid route-grid--executive">{routes.map(route=><article className="route-card route-card--executive" key={route.slug}><div className="route-card__meta"><span className={`access access--${route.access}`}>{route.access}</span><span className={`route-state route-state--${route.status}`}>{route.status}</span></div><div className="eyebrow">{route.eyebrow}</div><h4>{route.title}</h4><p>{route.description}</p><div className="route-card__footer"><span>{route.triggers.length} triggers · {route.apiEndpoints.length} API contracts</span><Link href={`/${route.slug}`}>Open module →</Link></div></article>)}</div></section>)}</div></section>

  <section className="enterprise-cta"><div className="container enterprise-cta__grid"><div><div className="eyebrow">Enterprise Tax Operations</div><h2>Build a stronger firm around one controlled operating system.</h2><p>Unify intake, preparation, review, e-file control, client communication, notices, refund intelligence, payroll, compliance, analytics, education, and release governance under the Ross Tax Pro standard.</p></div><div className="enterprise-cta__actions"><Link className="ross-btn ross-btn--gold" href="/start">Begin Secure Intake</Link><Link className="ross-btn ross-btn--outline hero-outline" href="/contact">Request Enterprise Consultation</Link></div></div></section>
 </>;
}
