import Link from 'next/link';
import {groupedRoutes,platformRoutes} from '../lib/routes';
import {CONTROL_GATES,TASK_STATES} from '../lib/operations';

const implemented=platformRoutes.filter(route=>route.status==='implemented').length;
const controlled=platformRoutes.filter(route=>route.status==='controlled').length;
const externalGate=platformRoutes.filter(route=>route.status==='external-gate').length;
const protectedRoutes=platformRoutes.filter(route=>route.access!=='public').length;

const pillars=[
 {title:'Prepare with precision',subtitle:'Guided tax workflow',text:'Structured intake, document validation, due diligence, workpapers, review gates, signatures, transmission readiness, and exception handling.',href:'/practitioner-work-zone',cta:'Open practitioner operations'},
 {title:'Operate the entire practice',subtitle:'RTPSC Operations Fabric',text:'Manage clients, preparers, returns, acknowledgments, notices, refund evidence, tasks, communications, compliance, releases, and operational exceptions.',href:'/operations-fabric',cta:'Open Operations Fabric'},
 {title:'Turn evidence into action',subtitle:'ETRAC intelligence',text:'Normalize authorized events from acknowledgments, transcripts, notices, refund evidence, payroll, identity, and portals into controlled queues and client-safe status narratives.',href:'/analytics',cta:'Review intelligence controls'}
];

export default function HomePage(){
 return <>
  <section className="hero hero--brand"><div className="container hero-grid hero-grid--brand">
   <div><div className="eyebrow">Ross Tax Pro Software Co. · RTPSC Operations Fabric</div><h1>Smarter software.<br/>Stronger practice results.</h1><p className="lead">A governed, multi-tenant tax operating system for client intake, practitioner work, e-file controls, authorized transcript workflows, refund intelligence, notices, payroll, AI-assisted tasks, analytics, compliance, infrastructure, and release governance.</p><div className="actions"><Link className="ross-btn ross-btn--gold" href="/start">Start Secure Client Intake</Link><Link className="ross-btn ross-btn--outline hero-outline" href="/operations-fabric">Enter the Operations Fabric</Link></div><div className="hero-meta"><span>Deny by default</span><span>MFA + RBAC</span><span>Immutable evidence</span><span>Human accountability</span><span>External adapters fail closed</span></div></div>
   <aside className="brand-showcase" aria-label="Ross Tax Pro platform status"><img src="/assets/ross-brand-mark.svg" alt="Ross Tax Pro Software Co."/><div className="brand-showcase__status"><span className="status-dot"/><div><b>Application control plane operational</b><small>Regulated external connections remain credential, authorization, and evidence gated.</small></div></div><div className="brand-showcase__actions"><Link href="/api/health">System health</Link><Link href="/api/platform/status">Runtime status</Link><Link href="/api/v1/operations/overview">Operations API</Link></div></aside>
  </div></section>

  <section className="section section--compact"><div className="container stat-grid"><article className="stat-card"><strong>{platformRoutes.length}</strong><span>Registered application routes</span></article><article className="stat-card"><strong>{CONTROL_GATES.length}</strong><span>Mandatory control gates</span></article><article className="stat-card"><strong>{TASK_STATES.length}</strong><span>Governed task states</span></article><article className="stat-card"><strong>{externalGate}</strong><span>External authorization gates</span></article></div></section>

  <section className="section"><div className="container"><div className="section-heading"><div><div className="eyebrow">Practice Operating System</div><h2>Implemented beyond a return-entry screen.</h2></div><p>The deployment now registers each platform surface with access level, workflow, task triggers, API contracts, integration boundaries, and operational discipline.</p></div><div className="pillar-grid">{pillars.map(p=><article className="pillar-card" key={p.title}><span>{p.subtitle}</span><h3>{p.title}</h3><p>{p.text}</p><Link href={p.href}>{p.cta} →</Link></article>)}</div></div></section>

  <section className="section section--etrac"><div className="container etrac-grid"><div className="etrac-visual"><img src="/assets/etrac-mark.svg" alt="ETRAC governed event intelligence"/></div><div><div className="eyebrow">ETRAC Event Intelligence</div><h2>Route every verified event through the next correct control.</h2><p>Intake, uploads, signatures, acknowledgments, notices, refund evidence, payments, and security anomalies now map to executable trigger definitions, task creation, gate assignment, human-review requirements, and audit event identifiers.</p><ul className="check-list"><li>15 mandatory tax-operation gates</li><li>16 task and exception states</li><li>PASS, FLAG, HOLD, and DENY decisions</li><li>Human approval before material transitions</li></ul><div className="actions"><Link className="ross-btn ross-btn--gold" href="/operations-fabric">Inspect Operations Fabric</Link><Link className="ross-btn ross-btn--outline hero-outline" href="/api/v1/integrations">Review Adapter Registry</Link></div></div></div></section>

  <section className="section" id="platform-directory"><div className="container"><div className="section-heading"><div><div className="eyebrow">Application Directory</div><h2>Every surface has a purpose, access contract, workflow, triggers, and APIs.</h2></div><p><b>Implemented</b> means the page and internal contract exist. <b>Controlled</b> means identity, role, and policy enforcement is required. <b>External gate</b> means the adapter remains unable to contact an outside system until verified authorization and configuration evidence exists.</p></div>
   <div className="status-strip"><span>{implemented} implemented</span><span>{controlled} controlled</span><span>{externalGate} external-gate</span><span>{protectedRoutes} protected</span></div>
   {Object.entries(groupedRoutes).map(([category,routes])=>routes.length>0&&<section className="route-group" key={category} aria-labelledby={`group-${category.replaceAll(' ','-').toLowerCase()}`}><div className="route-group__heading"><h3 id={`group-${category.replaceAll(' ','-').toLowerCase()}`}>{category}</h3><span>{routes.length} routes</span></div><div className="route-grid">{routes.map(route=><article className="route-card" key={route.slug}><div className="route-card__meta"><span className={`access access--${route.access}`}>{route.access}</span><span className={`route-state route-state--${route.status}`}>{route.status}</span></div><div className="eyebrow">{route.eyebrow}</div><h4>{route.title}</h4><p>{route.description}</p><ul>{route.capabilities.slice(0,3).map(capability=><li key={capability}>{capability}</li>)}</ul><Link className="card-link" href={`/${route.slug}`}>Open {route.title} →</Link></article>)}</div></section>)}
  </div></section>

  <section className="section section--dark"><div className="container callout-grid"><div><div className="eyebrow">Production Discipline</div><h2>Implemented does not mean externally authorized.</h2><p>The route registry, workflow engine, trigger engine, reconciliation logic, refund inference, AI task policy, e-file gate contract, and adapter registry are implemented. IRS, TDS, SOR, TIN Matching, IRIS, payment, payroll, messaging, and Apple connections remain disabled until approvals, credentials, certificates, allowlists, tests, owner approval, and operating evidence are installed.</p></div><div className="callout-actions"><Link className="ross-btn ross-btn--gold" href="/compliance">Review Security Controls</Link><Link className="ross-btn ross-btn--outline hero-outline" href="/documentation">Open Documentation</Link></div></div></section>
 </>;
}
