import {createHash} from 'node:crypto';
import type {RefundCase,RefundState,SourceSystem,Station,Trigger} from './refund-case';
import {activeAuthorization,reconcileRefundCase,runWorkflow} from './refund-case';

export type SyncIndicatorSeverity='INFO'|'LOW'|'MODERATE'|'HIGH'|'CRITICAL';
export type SourceFreshness='CURRENT'|'AGING'|'STALE'|'UNKNOWN';
export type RefundLifecycleIndicator={id:string;kind:'RETURN'|'IDENTITY'|'TRANSCRIPT_TC'|'TREASURY'|'BANK_PRODUCT'|'NOTICE'|'AUTHORIZATION'|'CONFLICT'|'LIFECYCLE';code:string;label:string;severity:SyncIndicatorSeverity;observedAt:string;sourceSystem:SourceSystem|'WORKSPACEIRS';evidenceIds:string[];narrative:string;requiresHumanReview:boolean;officialAgencyDetermination:false};
export type MasterfileSnapshot={snapshotId:string;caseId:string;tenantId:string;taxpayerId:string;taxYear:number;generatedAt:string;sourceCutoffAt:string|null;refundState:RefundState;caseStatus:'OPEN'|'HOLD'|'CLOSED';confidence:number;currentStation:Station;authorizationActive:boolean;freshness:Record<string,SourceFreshness>;indicators:RefundLifecycleIndicator[];triggers:Trigger[];routes:{trigger:Trigger;from:Station;to:Station;actions:string[]}[];controllingEvidenceIds:string[];conflicts:string[];humanReviewRequired:boolean;sync:{mode:'AUTHORIZED_DOWNSTREAM';externalRetrievalPerformed:false;agencyStateClaimed:false;deterministic:true;fingerprint:string}};

const nowIso=()=>new Date().toISOString();
const freshness=(value?:string|null):SourceFreshness=>{if(!value)return 'UNKNOWN';const hours=(Date.now()-new Date(value).getTime())/3600000;return hours<=24?'CURRENT':hours<=168?'AGING':'STALE'};
const id=(caseId:string,code:string,evidenceIds:string[])=>'ind_'+createHash('sha256').update([caseId,code,...[...evidenceIds].sort()].join('|')).digest('hex').slice(0,20);
const make=(caseId:string,input:Omit<RefundLifecycleIndicator,'id'|'officialAgencyDetermination'>):RefundLifecycleIndicator=>({...input,id:id(caseId,input.code,input.evidenceIds),officialAgencyDetermination:false});
const newest=(values:(string|null|undefined)[])=>values.filter((v):v is string=>Boolean(v)).sort().at(-1)??null;

export function buildRefundIndicators(c:RefundCase):RefundLifecycleIndicator[]{
 const out:RefundLifecycleIndicator[]=[];
 for(const e of c.returns)out.push(make(c.caseId,{kind:'RETURN',code:`RETURN_${e.acceptanceStatus}`,label:`Return ${e.acceptanceStatus.toLowerCase()}`,severity:e.acceptanceStatus==='REJECTED'?'HIGH':'INFO',observedAt:e.transmissionDate??nowIso(),sourceSystem:(e.softwareSystem as SourceSystem)||'OTHER',evidenceIds:[e.id],narrative:`Tax software reported ${e.acceptanceStatus.toLowerCase()} status.`,requiresHumanReview:e.acceptanceStatus==='REJECTED'}));
 for(const t of c.transcripts)for(const tc of t.transactionCodes)out.push(make(c.caseId,{kind:'TRANSCRIPT_TC',code:`TC_${tc.code}`,label:`Transaction code ${tc.code}`,severity:tc.code==='810'?'CRITICAL':tc.code==='570'?'HIGH':'INFO',observedAt:tc.date,sourceSystem:'IRS_TDS',evidenceIds:[t.id],narrative:`Authorized transcript contains TC ${tc.code}.`,requiresHumanReview:['570','810'].includes(tc.code)}));
 for(const e of c.treasury)out.push(make(c.caseId,{kind:'TREASURY',code:`TREASURY_${e.status}`,label:`Treasury ${e.status.toLowerCase()}`,severity:['RETURNED','OFFSET'].includes(e.status)?'HIGH':'INFO',observedAt:e.paymentDate??nowIso(),sourceSystem:e.status==='OFFSET'?'TREASURY_TOP':'TREASURY_BFS',evidenceIds:[e.id],narrative:`Authorized Treasury evidence reports ${e.status.toLowerCase()} status.`,requiresHumanReview:['RETURNED','OFFSET'].includes(e.status)}));
 for(const e of c.refundProducts)out.push(make(c.caseId,{kind:'BANK_PRODUCT',code:`BANK_${e.status}`,label:`Bank product ${e.status.toLowerCase()}`,severity:['REJECTED','RETURNED'].includes(e.status)?'HIGH':'INFO',observedAt:e.disbursedAt??e.fundedAt??nowIso(),sourceSystem:e.bankPartner==='SBTPG'?'BANK_SBTPG':e.bankPartner==='EPS'?'BANK_EPS':e.bankPartner==='REFUNDO'?'BANK_REFUNDO':'OTHER',evidenceIds:[e.id],narrative:`Approved bank-product evidence reports ${e.status.toLowerCase()} status.`,requiresHumanReview:['REJECTED','RETURNED'].includes(e.status)}));
 for(const e of c.identities)out.push(make(c.caseId,{kind:'IDENTITY',code:`IDENTITY_${e.status}`,label:`Identity ${e.status.toLowerCase()}`,severity:e.status==='FAILED'?'CRITICAL':e.status==='MANUAL_REVIEW'?'HIGH':'INFO',observedAt:nowIso(),sourceSystem:'IDENTITY_PROVIDER',evidenceIds:[e.id],narrative:`Identity provider reports ${e.status.toLowerCase()} status.`,requiresHumanReview:e.status!=='VERIFIED'}));
 for(const e of c.notices.filter(n=>n.status==='OPEN'))out.push(make(c.caseId,{kind:'NOTICE',code:`NOTICE_${e.noticeType}`,label:`Open ${e.noticeType} notice`,severity:'HIGH',observedAt:e.issueDate,sourceSystem:'IRS_ONLINE_ACCOUNT',evidenceIds:[e.id],narrative:`Open notice ${e.noticeType} requires controlled resolution.`,requiresHumanReview:true}));
 if(!activeAuthorization(c))out.push(make(c.caseId,{kind:'AUTHORIZATION',code:'AUTH_SCOPE_INACTIVE',label:'Authorization scope inactive',severity:'CRITICAL',observedAt:nowIso(),sourceSystem:'WORKSPACEIRS',evidenceIds:c.authorizations.map(a=>a.id),narrative:'No active authorization covers this case and tax year.',requiresHumanReview:true}));
 const r=reconcileRefundCase(c);for(const conflict of r.conflicts)out.push(make(c.caseId,{kind:'CONFLICT',code:'EVIDENCE_CONFLICT',label:'Evidence conflict detected',severity:'CRITICAL',observedAt:nowIso(),sourceSystem:'WORKSPACEIRS',evidenceIds:r.controllingEvidenceIds,narrative:conflict,requiresHumanReview:true}));
 out.push(make(c.caseId,{kind:'LIFECYCLE',code:`STATE_${r.state}`,label:r.state.replaceAll('_',' '),severity:r.humanReviewRequired?'HIGH':'INFO',observedAt:nowIso(),sourceSystem:'WORKSPACEIRS',evidenceIds:r.controllingEvidenceIds,narrative:`Best-supported refund lifecycle state is ${r.state}.`,requiresHumanReview:r.humanReviewRequired}));
 return out.sort((a,b)=>a.observedAt.localeCompare(b.observedAt)||a.code.localeCompare(b.code));
}

export function synchronizeMasterfile(c:RefundCase,previousState?:RefundState):MasterfileSnapshot{
 const workflow=runWorkflow(c,previousState);const indicators=buildRefundIndicators(c);
 const dates={transcript:newest(c.evidence.filter(e=>e.evidenceType==='TRANSCRIPT').map(e=>e.receivedAt)),treasury:newest(c.evidence.filter(e=>e.evidenceType==='TREASURY_PAYMENT').map(e=>e.receivedAt)),bank:newest(c.evidence.filter(e=>e.evidenceType==='BANK_PRODUCT').map(e=>e.receivedAt)),return:newest(c.evidence.filter(e=>e.evidenceType==='RETURN').map(e=>e.receivedAt)),identity:newest(c.evidence.filter(e=>e.evidenceType==='IDENTITY').map(e=>e.receivedAt)),notice:newest(c.evidence.filter(e=>e.evidenceType==='NOTICE').map(e=>e.receivedAt))};
 const sourceCutoffAt=newest(Object.values(dates));const base={caseId:c.caseId,taxYear:c.taxYear,state:workflow.reconciliation.state,status:workflow.caseStatus,sourceCutoffAt,indicatorIds:indicators.map(i=>i.id),triggers:workflow.triggers,routes:workflow.routes};const fingerprint=createHash('sha256').update(JSON.stringify(base)).digest('hex');
 return {snapshotId:`mfs_${fingerprint.slice(0,24)}`,caseId:c.caseId,tenantId:c.tenantId,taxpayerId:c.taxpayerId,taxYear:c.taxYear,generatedAt:nowIso(),sourceCutoffAt,refundState:workflow.reconciliation.state,caseStatus:workflow.caseStatus,confidence:workflow.reconciliation.confidence,currentStation:c.currentStation,authorizationActive:activeAuthorization(c),freshness:Object.fromEntries(Object.entries(dates).map(([k,v])=>[k,freshness(v)])),indicators,triggers:workflow.triggers,routes:workflow.routes,controllingEvidenceIds:workflow.reconciliation.controllingEvidenceIds,conflicts:workflow.reconciliation.conflicts,humanReviewRequired:workflow.requiresHumanReview,sync:{mode:'AUTHORIZED_DOWNSTREAM',externalRetrievalPerformed:false,agencyStateClaimed:false,deterministic:true,fingerprint}};
}

export function synchronizeMasterfiles(cases:RefundCase[],previousStates:Record<string,RefundState>={}){
 const grouped=new Map<string,RefundCase>();for(const c of cases){const key=`${c.tenantId}|${c.taxpayerId}|${c.taxYear}`;const prior=grouped.get(key);if(!prior||c.evidence.length>=prior.evidence.length)grouped.set(key,c)}
 return [...grouped.values()].map(c=>synchronizeMasterfile(c,previousStates[c.caseId])).sort((a,b)=>a.taxpayerId.localeCompare(b.taxpayerId)||a.taxYear-b.taxYear);
}
