export type AccessLevel='public'|'authenticated'|'restricted';
export type RouteStatus='available'|'gated'|'planned';
export type RouteCategory='Public Services'|'Client Operations'|'ERO Operations'|'Administration'|'Education';

export type PlatformRoute={
 slug:string;
 title:string;
 eyebrow:string;
 subtitle:string;
 description:string;
 cta:string;
 ctaHref:string;
 access:AccessLevel;
 status:RouteStatus;
 category:RouteCategory;
 capabilities:string[];
 integrations:string[];
};

export const platformRoutes:PlatformRoute[]=[
 {slug:'services',title:'Tax and Software Services',eyebrow:'Professional Services',subtitle:'Secure operations from intake through resolution.',description:'Explore tax preparation, payroll, compliance, transcript operations, software solutions, and practitioner support.',cta:'Start Secure Intake',ctaHref:'/start',access:'public',status:'available',category:'Public Services',capabilities:['Individual and business tax services','Payroll and compliance operations','Software implementation support','Case and notice assistance'],integrations:['Secure intake','Document collection','Workflow routing']},
 {slug:'about',title:'Built for Accountable Tax Operations',eyebrow:'Company',subtitle:'Smarter Software. Stronger Results.',description:'Ross Tax Pro Software Co. combines practitioner workflows, controlled automation, auditability, and client service.',cta:'Review Our Standards',ctaHref:'/compliance',access:'public',status:'available',category:'Public Services',capabilities:['Governed workflows','Role-based operations','Evidence-driven controls','Multi-tenant architecture'],integrations:['Audit trail','Policy controls','Reporting']},
 {slug:'resources',title:'Professional Resource Center',eyebrow:'Resources',subtitle:'Guides, workflows, notices, and operational references.',description:'Access approved public resources while taxpayer records remain protected behind authenticated controls.',cta:'Browse Services',ctaHref:'/services',access:'public',status:'available',category:'Public Services',capabilities:['Taxpayer guides','Notice references','Workflow checklists','Training resources'],integrations:['Content library','Search','Version control']},
 {slug:'contact',title:'Contact Ross Tax Pro',eyebrow:'Contact',subtitle:'Professional service with documented follow-through.',description:'Contact the company for enterprise, software, tax-practice, partnership, or implementation inquiries.',cta:'Email Our Team',ctaHref:'mailto:ceo@rosstaxsoftware.com',access:'public',status:'available',category:'Public Services',capabilities:['Enterprise inquiries','Implementation planning','Professional support','Partnership intake'],integrations:['Email routing','Case assignment','Service tracking']},
 {slug:'start',title:'Start Secure Intake',eyebrow:'Onboarding',subtitle:'Begin with identity, consent, and engagement verification.',description:'Production intake connects identity, engagement, document, and consent workflows before taxpayer information is processed.',cta:'Open Client Portal',ctaHref:'/portal',access:'public',status:'available',category:'Client Operations',capabilities:['Identity verification','Engagement acceptance','Consent capture','Document checklist'],integrations:['Identity provider','E-signature','Document vault']},
 {slug:'portal',title:'Client Portal',eyebrow:'Client Operations',subtitle:'Documents, signatures, notices, and case status.',description:'Authenticated client access for secure records, requests, signatures, notices, and case progress.',cta:'Check Platform Status',ctaHref:'/api/platform/status',access:'authenticated',status:'gated',category:'Client Operations',capabilities:['Secure document exchange','Signature requests','Case timeline','Message center'],integrations:['Authentication','Storage','Notifications','Audit trail']},
 {slug:'notices',title:'Notice and Resolution Center',eyebrow:'Client Operations',subtitle:'Organized response workflows for tax notices and verification requests.',description:'Routes notice intake, evidence requests, assignments, due dates, approvals, and response packages through controlled case workflows.',cta:'Review Compliance',ctaHref:'/compliance',access:'authenticated',status:'gated',category:'Client Operations',capabilities:['Notice classification','Deadline tracking','Evidence checklist','Response package review'],integrations:['Case management','Document vault','Notifications']},
 {slug:'ero',title:'ERO Workspace',eyebrow:'ERO Operations',subtitle:'Return pipeline, acknowledgments, rejects, and funding operations.',description:'Restricted workspace for authorized ERO personnel with MFA, RBAC, controlled transmission gates, and complete audit logging.',cta:'Check Platform Status',ctaHref:'/api/platform/status',access:'restricted',status:'gated',category:'ERO Operations',capabilities:['Return pipeline','Acknowledgment processing','Reject resolution','Funding status'],integrations:['Identity and RBAC','E-file adapters','Acknowledgments','Audit trail']},
 {slug:'transcripts',title:'Transcript Center',eyebrow:'ERO Operations',subtitle:'Authorized request tracking and transcript intelligence.',description:'TDS and SOR features remain gated until authorizations, certificates, endpoints, allowlists, and production validation are recorded.',cta:'View Connection Status',ctaHref:'/api/platform/status',access:'restricted',status:'gated',category:'ERO Operations',capabilities:['Authorization tracking','Request lifecycle','Transcript parsing','Account-code alerts'],integrations:['IRS TDS','IRS SOR','Document vault','Audit trail']},
 {slug:'refunds',title:'Refund Intelligence',eyebrow:'ERO Operations',subtitle:'Funding, fee, exception, and case analytics.',description:'Combines verified records and authorized provider data without presenting estimates as official determinations.',cta:'View Connection Status',ctaHref:'/api/platform/status',access:'restricted',status:'gated',category:'ERO Operations',capabilities:['Funding lanes','Exception queues','Fee reconciliation','Case analytics'],integrations:['Authorized IRS data','Funding providers','Reporting']},
 {slug:'payroll',title:'Payroll Operations',eyebrow:'Operations',subtitle:'Employees, earnings, deductions, filings, and statements.',description:'Controlled payroll workflows with approvals, reconciliation, reporting, exception handling, and retention.',cta:'Review Services',ctaHref:'/services',access:'authenticated',status:'planned',category:'Administration',capabilities:['Employee records','Pay-run approvals','Tax reconciliation','Statements and reporting'],integrations:['Payroll engine','Banking adapters','Tax filing services','Notifications']},
 {slug:'admin',title:'Administration Center',eyebrow:'Administration',subtitle:'Tenants, users, credentials, policies, and system controls.',description:'Restricted administration for users, roles, tenant configuration, integration gates, policies, and operational evidence.',cta:'System Health',ctaHref:'/api/health',access:'restricted',status:'gated',category:'Administration',capabilities:['Tenant administration','User and role management','Policy configuration','Integration controls'],integrations:['Identity provider','Secrets manager','Audit trail','Observability']},
 {slug:'compliance',title:'Security and Compliance',eyebrow:'Governance',subtitle:'MFA, RBAC, encryption, WISP, logging, and retention.',description:'Controls are designed around least privilege, evidence preservation, approval gates, secure defaults, and incident response.',cta:'Platform Status',ctaHref:'/api/platform/status',access:'public',status:'available',category:'Administration',capabilities:['Written security program','Access controls','Evidence retention','Incident response'],integrations:['Security monitoring','Encryption','Audit logging','Policy engine']},
 {slug:'academy',title:'Ross Tax Academy',eyebrow:'Education',subtitle:'Structured tax, accounting, software, and compliance education.',description:'A governed learning environment for professional development, practitioner training, assessments, and curriculum delivery.',cta:'Browse Resources',ctaHref:'/resources',access:'public',status:'planned',category:'Education',capabilities:['Course catalog','Learning paths','Assessments','Completion records'],integrations:['Learning management','Content library','Reporting']}
];

export const primaryNavigation=platformRoutes.filter(route=>['services','resources','compliance','contact'].includes(route.slug));
export const getRoute=(slug:string)=>platformRoutes.find(route=>route.slug===slug);
export const groupedRoutes=platformRoutes.reduce<Record<RouteCategory,PlatformRoute[]>>((groups,route)=>{
 groups[route.category].push(route);
 return groups;
},{'Public Services':[],'Client Operations':[],'ERO Operations':[],'Administration':[],'Education':[]});
