export type AccessLevel='public'|'authenticated'|'restricted';
export type RouteStatus='implemented'|'controlled'|'external-gate';
export type RouteCategory='Platform Foundation'|'Client Operations'|'Tax Operations'|'Intelligence Fabric'|'Governance'|'Administration'|'Education and Release';

export type PlatformRoute={
 slug:string;
 title:string;
 eyebrow:string;
 subtitle:string;
 description:string;
 cta:string;
 ctaHref:string;
 access:AccessLevel;
 status:RouteStatus;
 category:RouteCategory;
 capabilities:string[];
 integrations:string[];
 workflow:string[];
 triggers:string[];
 apiEndpoints:string[];
};

export const platformRoutes:PlatformRoute[]=[
 {slug:'foundation',title:'Platform Foundation',eyebrow:'Control Architecture',subtitle:'Identity, tenancy, evidence, policy, and execution boundaries.',description:'Defines the mandatory platform frame: tenant isolation, role enforcement, evidence lineage, policy gates, event contracts, environment separation, and fail-closed adapters.',cta:'Inspect Operations Fabric',ctaHref:'/operations-fabric',access:'public',status:'implemented',category:'Platform Foundation',capabilities:['Tenant and office boundaries','Identity, MFA, RBAC, and session controls','Evidence lineage and immutable audit envelopes','Environment and adapter separation'],integrations:['Identity plane','Policy engine','Evidence vault','Audit and observability'],workflow:['Identify scope','Evaluate authorization','Issue short-lived decision','Execute allowed action','Preserve evidence'],triggers:['SECURITY_ANOMALY','INTAKE_SUBMITTED'],apiEndpoints:['GET /api/health','GET /api/platform/status','GET /api/v1/integrations']},
 {slug:'operations-fabric',title:'RTPSC Operations Fabric',eyebrow:'Operational Control Plane',subtitle:'Portfolio health, queues, gates, tasks, exceptions, and release state.',description:'The central governed workspace for route health, task queues, adapter readiness, workflow state, event triggers, exception escalation, and controlled release evidence.',cta:'Open Operations API',ctaHref:'/api/v1/operations/overview',access:'restricted',status:'controlled',category:'Platform Foundation',capabilities:['Operational queue visibility','Control-gate and task-state registry','Adapter readiness matrix','Exception and escalation routing'],integrations:['Workflow engine','Task trigger engine','Event bus','Observability plane'],workflow:['Observe','Prioritize','Assign','Approve','Execute','Verify','Retain'],triggers:['SECURITY_ANOMALY','EFILE_ACK_RECEIVED','NOTICE_UPLOADED'],apiEndpoints:['GET /api/v1/operations/overview','POST /api/v1/workflows/transition','POST /api/v1/workflows/triggers']},
 {slug:'enterprise-experience',title:'Enterprise Experience Fabric',eyebrow:'Experience and Service Architecture',subtitle:'Role-specific themes, service dossiers, explicit actions, guarded transitions, mobile delivery, and GitHub release evidence.',description:'A non-generic enterprise presentation and routing layer for luxury service commerce, taxpayer concierge, practitioner production, ERO command, bookkeeping, payroll, AI employees, education, administration, and multi-office scale.',cta:'Open Enterprise Experience',ctaHref:'/enterprise-experience',access:'public',status:'implemented',category:'Platform Foundation',capabilities:['Eight role-specific visual systems','Coded luxury service exchange','Explicit domain-action vocabulary','Guarded state-transition registry','Mobile and Node orchestration surfaces'],integrations:['Service catalog package','Experience-system package','Workflow engine','Node orchestration gateway','GitHub release workflows'],workflow:['Discover service','Approve scope and price','Collect evidence','Execute controlled work','Human review','Release and retain'],triggers:['INTAKE_SUBMITTED','PAYMENT_CONFIRMED','DOCUMENT_UPLOADED','SECURITY_ANOMALY'],apiEndpoints:['GET /api/v1/enterprise/catalog','POST /api/v1/enterprise/transitions','GET /api/ready']},
 {slug:'services',title:'Tax and Software Services',eyebrow:'Professional Services',subtitle:'Secure operations from intake through resolution.',description:'Professional tax, payroll, notice, software implementation, and compliance services routed through documented scope, pricing, assignment, approval, delivery, and retention controls.',cta:'Start Secure Intake',ctaHref:'/start',access:'public',status:'implemented',category:'Client Operations',capabilities:['Individual and business tax services','Payroll and compliance operations','Software implementation support','Notice and case assistance'],integrations:['Secure intake','Service-order routing','Document collection','Billing controls'],workflow:['Request service','Scope engagement','Approve price','Collect evidence','Deliver and acknowledge'],triggers:['INTAKE_SUBMITTED','PAYMENT_CONFIRMED'],apiEndpoints:['POST /api/v1/workflows/triggers','POST /api/v1/workflows/transition']},
 {slug:'start',title:'Start Secure Intake',eyebrow:'Onboarding',subtitle:'Begin with identity, consent, conflict, engagement, and document gates.',description:'Creates a controlled onboarding path before taxpayer information is processed or a service engagement is accepted.',cta:'Open Client Portal',ctaHref:'/client-portal',access:'public',status:'implemented',category:'Client Operations',capabilities:['Identity verification request','Conflict-screening workflow','Engagement and consent capture','Document and deadline checklist'],integrations:['Identity provider','E-signature','Evidence vault','Notification service'],workflow:['INTAKE','IDENTITY','CONFLICT','ENGAGEMENT','DOCUMENTS'],triggers:['INTAKE_SUBMITTED','DOCUMENT_UPLOADED'],apiEndpoints:['POST /api/v1/workflows/triggers','POST /api/v1/workflows/transition']},
 {slug:'client-portal',title:'Client Portal',eyebrow:'Client Operations',subtitle:'Onboarding, uploads, questionnaires, signatures, payments, and delivery.',description:'Authenticated taxpayer workspace for secure document exchange, questionnaires, engagement records, signature requests, notice uploads, payment requests, status narratives, and delivery acknowledgments.',cta:'Inspect Platform Status',ctaHref:'/api/platform/status',access:'authenticated',status:'controlled',category:'Client Operations',capabilities:['Secure document exchange','Questionnaire and missing-item requests','Signature and approval evidence','Case timeline and delivery acknowledgment'],integrations:['Identity and MFA','Evidence vault','E-signature','Payments and notifications'],workflow:['AUTHENTICATED','SCOPED','PRICED_APPROVED','IN_PROGRESS','DELIVERED','ACKNOWLEDGED','RETAINED'],triggers:['DOCUMENT_UPLOADED','SIGNATURE_COMPLETED','PAYMENT_CONFIRMED'],apiEndpoints:['POST /api/v1/workflows/triggers','POST /api/v1/workflows/transition']},
 {slug:'service-hub',title:'Service Provider Support Hub',eyebrow:'Client Operations',subtitle:'Authenticated inquiry, SLA, assignment, escalation, QA, and closure.',description:'Routes client and provider support through identity verification, case context, source-linked replies, service-level controls, supervisor escalation, quality review, and evidence retention.',cta:'Open Workflow Registry',ctaHref:'/api/v1/operations/overview',access:'authenticated',status:'controlled',category:'Client Operations',capabilities:['Authenticated inquiry intake','SLA and queue management','Source-linked response drafting','Escalation and QA review'],integrations:['Case management','Knowledge library','Notifications','Audit trail'],workflow:['REQUESTED','AUTHENTICATED','SCOPED','QUEUED','IN_PROGRESS','HUMAN_REVIEW','DELIVERED','ACKNOWLEDGED'],triggers:['INTAKE_SUBMITTED','SECURITY_ANOMALY'],apiEndpoints:['POST /api/v1/workflows/transition','POST /api/v1/ai/tasks']},
 {slug:'notices',title:'Notice and Resolution Center',eyebrow:'Client Operations',subtitle:'Deadline-aware notice triage, evidence, review, response, and delivery.',description:'Controls notice intake, page preservation, classification, apparent deadlines, authority checks, assignments, response workpapers, approvals, delivery, and follow-up evidence.',cta:'Review Compliance',ctaHref:'/compliance',access:'authenticated',status:'controlled',category:'Client Operations',capabilities:['Notice classification','Apparent deadline extraction','Evidence and authority checklist','Response package review'],integrations:['Case management','Evidence vault','Notifications','Practitioner work zone'],workflow:['REQUESTED','AUTHENTICATED','SCOPED','IN_PROGRESS','HUMAN_REVIEW','DELIVERED','ACKNOWLEDGED','RETAINED'],triggers:['NOTICE_UPLOADED','DOCUMENT_UPLOADED'],apiEndpoints:['POST /api/v1/workflows/triggers','POST /api/v1/ai/tasks']},
 {slug:'practitioner-work-zone',title:'Practitioner Work Zone',eyebrow:'Tax Operations',subtitle:'Cases, workpapers, reviews, notices, representation, and RACI.',description:'Restricted professional workspace for return preparation, workpaper lineage, due-diligence interviews, reviewer notes, notice matters, authorization records, assignments, and separation of duties.',cta:'Open E-file Workbench',ctaHref:'/efile-workbench',access:'restricted',status:'controlled',category:'Tax Operations',capabilities:['Case and workpaper management','Due-diligence records','Reviewer disposition and overrides','Authority and representation tracking'],integrations:['Return engine','Evidence vault','TDS/CAF vault','Audit trail'],workflow:['PREP','DUE_DILIGENCE','REVIEW','CLIENT_APPROVAL','SIGNATURE'],triggers:['DOCUMENT_UPLOADED','SIGNATURE_COMPLETED','NOTICE_UPLOADED'],apiEndpoints:['POST /api/v1/masterfile/reconcile','POST /api/v1/workflows/transition']},
 {slug:'efile-workbench',title:'E-file Workbench',eyebrow:'Tax Operations',subtitle:'Validation, approval, submission intent, acknowledgments, rejects, and retries.',description:'Implements the controlled MeF submission lifecycle. The application logic is active; transmission remains fail-closed until provider roles, active schemas, ATS evidence, certificates, endpoints, and owner approval are verified.',cta:'Inspect Adapter Registry',ctaHref:'/api/v1/integrations',access:'restricted',status:'external-gate',category:'Tax Operations',capabilities:['Schema and business-rule gate','Human approval and signature gate','Idempotency and duplicate protection','Acknowledgment and reject correlation'],integrations:['IRS MeF gateway','Schema registry','Worker queue and DLQ','Immutable acknowledgment vault'],workflow:['REVIEW','CLIENT_APPROVAL','SIGNATURE','TRANSMIT','ACK','DELIVERY','RETENTION'],triggers:['SIGNATURE_COMPLETED','EFILE_ACK_RECEIVED','SECURITY_ANOMALY'],apiEndpoints:['POST /api/v1/efile/submissions','POST /api/v1/workflows/triggers','POST /api/v1/workflows/transition']},
 {slug:'tds-caf-vault',title:'TDS and CAF Authorization Vault',eyebrow:'Tax Operations',subtitle:'Authority, request ledgers, artifacts, access evidence, and retention.',description:'Tracks authorized transcript and representation workflows without credential sharing. External TDS/SOR use remains disabled until eligible access, client authority, certificates, and approved operating procedures are evidenced.',cta:'Inspect Integration Status',ctaHref:'/api/platform/status',access:'restricted',status:'external-gate',category:'Tax Operations',capabilities:['2848/8821 authority registry','Request transaction ledger','Artifact integrity and retention','Access and purpose evidence'],integrations:['IRS TDS','IRS SOR','Evidence vault','Masterfile reconciliation'],workflow:['AUTHENTICATED','SCOPED','HUMAN_REVIEW','DELIVERED','ACKNOWLEDGED','RETAINED'],triggers:['DOCUMENT_UPLOADED','SECURITY_ANOMALY'],apiEndpoints:['GET /api/v1/integrations','POST /api/v1/workflows/transition']},
 {slug:'payroll',title:'Payroll Operations',eyebrow:'Tax Operations',subtitle:'Employees, earnings, deductions, approvals, filings, and statements.',description:'Controlled payroll workflows for employee records, time exceptions, pay-run approvals, tax reconciliation, statements, filings, notifications, and retention.',cta:'Inspect Integration Status',ctaHref:'/api/v1/integrations',access:'restricted',status:'external-gate',category:'Tax Operations',capabilities:['Employee and earning records','Manager pay-run approval','Tax and liability reconciliation','Statements and filing evidence'],integrations:['Payroll engine','Payment rails','Tax filing services','Notifications'],workflow:['SCOPED','PRICED_APPROVED','QUEUED','IN_PROGRESS','HUMAN_REVIEW','DELIVERED','RETAINED'],triggers:['PAYMENT_CONFIRMED','SECURITY_ANOMALY'],apiEndpoints:['GET /api/v1/integrations','POST /api/v1/workflows/transition']},
 {slug:'refund-intelligence',title:'Refund Intelligence',eyebrow:'Intelligence Fabric',subtitle:'Evidence timelines, lanes, confidence, exceptions, and client-safe narratives.',description:'Infers a monitoring lane from governed evidence while preserving uncertainty. It never guarantees a refund, promises a date, or presents an inference as an official agency determination.',cta:'Open Inference Contract',ctaHref:'/api/v1/refund-intelligence/infer',access:'restricted',status:'controlled',category:'Intelligence Fabric',capabilities:['Evidence normalization','Refund lane inference','Confidence calculation','Exception and human-review routing'],integrations:['Authorized account artifacts','Funding-provider evidence','Case management','Notifications'],workflow:['REQUESTED','SCOPED','IN_PROGRESS','HUMAN_REVIEW','DELIVERED','ACKNOWLEDGED'],triggers:['REFUND_EVIDENCE_ADDED','SECURITY_ANOMALY'],apiEndpoints:['POST /api/v1/refund-intelligence/infer','POST /api/v1/workflows/triggers']},
 {slug:'masterfile-reconciliation',title:'Masterfile Reconciliation Suite',eyebrow:'Intelligence Fabric',subtitle:'Transcript-to-return and workpaper variance, materiality, and disposition.',description:'Compares authorized transcript observations and official artifacts to practitioner records. It does not claim direct access to the IRS internal Master File database.',cta:'Open Reconciliation Contract',ctaHref:'/api/v1/masterfile/reconcile',access:'restricted',status:'controlled',category:'Intelligence Fabric',capabilities:['Reported-versus-observed variance','Weighted materiality scoring','PASS, FLAG, and HOLD gates','Human disposition workflow'],integrations:['Authorized transcript artifacts','Return and workpaper engine','Evidence vault','Audit trail'],workflow:['SCOPED','IN_PROGRESS','FLAG','HOLD','HUMAN_REVIEW','DELIVERED'],triggers:['DOCUMENT_UPLOADED','SECURITY_ANOMALY'],apiEndpoints:['POST /api/v1/masterfile/reconcile','POST /api/v1/workflows/transition']},
 {slug:'ai-workforce',title:'AI Workforce Governance',eyebrow:'Intelligence Fabric',subtitle:'Persona registry, policy scope, task states, citations, review, and audit.',description:'Creates policy-scoped AI tasks for assistive work. AI cannot sign, transmit, represent, alter banking data, approve material actions, or clear a material HOLD.',cta:'Open AI Task Contract',ctaHref:'/api/v1/ai/tasks',access:'restricted',status:'controlled',category:'Intelligence Fabric',capabilities:['Persona and tool-scope registry','Risk-tier routing','Human-review enforcement','Prompt, source, output, and disposition audit'],integrations:['Approved model providers','Knowledge and citation layer','Workflow engine','Audit trail'],workflow:['REQUESTED','AUTHENTICATED','SCOPED','QUEUED','IN_PROGRESS','HUMAN_REVIEW','DELIVERED','RETAINED'],triggers:['NOTICE_UPLOADED','REFUND_EVIDENCE_ADDED','SECURITY_ANOMALY'],apiEndpoints:['POST /api/v1/ai/tasks','POST /api/v1/workflows/transition']},
 {slug:'analytics',title:'Analytics and Observability Plane',eyebrow:'Intelligence Fabric',subtitle:'Operations, quality, capacity, security, finance, and SLO evidence.',description:'Provides governed metrics from approved events without placing taxpayer identifiers, credentials, or unrestricted client facts in analytics dimensions or logs.',cta:'Open Operations Overview',ctaHref:'/api/v1/operations/overview',access:'restricted',status:'controlled',category:'Intelligence Fabric',capabilities:['Queue and cycle-time metrics','Quality and compliance indicators','Capacity and SLO reporting','Security and release evidence'],integrations:['Governed event warehouse','Audit logs','Monitoring and alarms','Financial reporting'],workflow:['Observe','Detect','Escalate','Correct','Verify'],triggers:['SECURITY_ANOMALY','EFILE_ACK_RECEIVED'],apiEndpoints:['GET /api/v1/operations/overview','GET /api/health']},
 {slug:'compliance',title:'Security and Compliance Center',eyebrow:'Governance',subtitle:'Policies, controls, evidence, findings, incidents, vendors, and attestations.',description:'Enforces least privilege, evidence preservation, approval gates, secure development, WISP controls, retention, incident response, vendor review, AI governance, and release discipline.',cta:'Inspect Runtime Health',ctaHref:'/api/health',access:'public',status:'implemented',category:'Governance',capabilities:['Written information security program','Policy and control evidence','Incident and vulnerability governance','Retention, legal hold, and secure deletion'],integrations:['Identity and access','Encryption and key management','Security monitoring','Audit and evidence vault'],workflow:['Identify control','Collect evidence','Test effectiveness','Remediate finding','Approve and retain'],triggers:['SECURITY_ANOMALY','DOCUMENT_UPLOADED'],apiEndpoints:['GET /api/health','GET /api/platform/status','GET /api/v1/integrations']},
 {slug:'admin',title:'Administration and Tenant Control',eyebrow:'Administration',subtitle:'Tenants, offices, users, roles, credentials, policies, adapters, and kill controls.',description:'Restricted administration for tenant boundaries, office hierarchy, invitations, role assignments, privileged approvals, integration gates, policy versions, evidence, suspension, and emergency lock controls.',cta:'Inspect Runtime Status',ctaHref:'/api/platform/status',access:'restricted',status:'controlled',category:'Administration',capabilities:['Tenant and office administration','User, role, and credential management','Adapter enablement and suspension','Policy versions and emergency controls'],integrations:['Identity provider','Secrets and key systems','Policy engine','Audit trail'],workflow:['Authenticate administrator','Verify privileged scope','Approve material change','Apply controlled change','Record and monitor'],triggers:['SECURITY_ANOMALY'],apiEndpoints:['GET /api/platform/status','GET /api/v1/integrations','POST /api/v1/workflows/transition']},
 {slug:'infrastructure',title:'Infrastructure and Reliability Center',eyebrow:'Administration',subtitle:'Accounts, environments, deployment, scaling, resilience, cost, and rollback.',description:'Documents and observes development, QA, staging, and production isolation; encrypted storage; queues; dead-letter handling; database resilience; monitoring; backups; restore exercises; and release rollback.',cta:'Inspect Health Endpoint',ctaHref:'/api/health',access:'restricted',status:'controlled',category:'Administration',capabilities:['Environment and account isolation','Queue, event, and dead-letter controls','Backup, restore, and disaster recovery','Scaling, SLO, budget, and rollback evidence'],integrations:['AWS Amplify Hosting','AWS data and event services','CloudWatch observability','DNS and certificates'],workflow:['Build','Validate','Stage','Approve','Release','Observe','Rollback or retain'],triggers:['SECURITY_ANOMALY'],apiEndpoints:['GET /api/health','GET /api/platform/status']},
 {slug:'documentation',title:'Documentation and Evidence Library',eyebrow:'Governance',subtitle:'Architecture, contracts, tests, releases, blockers, and operating records.',description:'Maintains controlled documentation for route contracts, API behavior, workflows, security policies, test evidence, production blockers, release approvals, and rollback records.',cta:'Inspect Route Registry',ctaHref:'/api/routes',access:'public',status:'implemented',category:'Governance',capabilities:['Architecture and API records','Workflow and policy documentation','Test and release evidence','Production-blocker register'],integrations:['Version control','Evidence vault','Release pipeline','Search and reporting'],workflow:['Author','Review','Approve','Publish','Supersede','Retain'],triggers:['DOCUMENT_UPLOADED'],apiEndpoints:['GET /api/routes','GET /api/v1/operations/overview']},
 {slug:'resources',title:'Professional Resource Center',eyebrow:'Education',subtitle:'Guides, checklists, notices, and approved operational references.',description:'Public and authenticated learning resources with controlled versions, source records, accessibility standards, and clear separation from client-specific records.',cta:'Browse Services',ctaHref:'/services',access:'public',status:'implemented',category:'Education and Release',capabilities:['Taxpayer and practitioner guides','Notice and workflow references','Versioned checklists','Accessible learning content'],integrations:['Content library','Search','Version control','Analytics'],workflow:['Draft','Review','Approve','Publish','Retain'],triggers:['DOCUMENT_UPLOADED'],apiEndpoints:['GET /api/routes']},
 {slug:'academy',title:'Ross Tax Academy',eyebrow:'Education',subtitle:'Tax, accounting, software, compliance, assessment, and completion records.',description:'Governed professional-learning environment for curriculum delivery, assignments, assessments, instructor review, completion evidence, and reporting.',cta:'Browse Resources',ctaHref:'/resources',access:'authenticated',status:'controlled',category:'Education and Release',capabilities:['Course and learning-path registry','Assignments and assessments','Instructor review','Completion and continuing-education records'],integrations:['Learning management','Content library','Identity and roles','Reporting'],workflow:['Enroll','Learn','Submit','Assess','Review','Complete','Retain'],triggers:['DOCUMENT_UPLOADED'],apiEndpoints:['POST /api/v1/workflows/transition']},
 {slug:'apple-release',title:'Apple Release Center',eyebrow:'Release Engineering',subtitle:'Native packaging, privacy manifest, signing, TestFlight, review, and rollback.',description:'Tracks Apple packaging and release evidence. Submission remains externally gated until membership, legal identity, signing assets, App Store Connect records, privacy review, owner authorization, and macOS/Xcode validation exist.',cta:'Inspect Integration Registry',ctaHref:'/api/v1/integrations',access:'restricted',status:'external-gate',category:'Education and Release',capabilities:['Bundle and capability registry','Privacy manifest and App Privacy review','Signing and TestFlight evidence','App Review, release, and rollback records'],integrations:['Apple Developer','App Store Connect','Signing and CI service','Release evidence vault'],workflow:['Package','Sign','Validate','TestFlight','Review','Approve','Release','Observe'],triggers:['SECURITY_ANOMALY'],apiEndpoints:['GET /api/v1/integrations','POST /api/v1/workflows/transition']},
 {slug:'about',title:'Built for Accountable Tax Operations',eyebrow:'Company',subtitle:'Smarter Software. Stronger Results.',description:'Ross Tax Pro Software Co. combines practitioner workflows, controlled automation, evidence-first architecture, professional service, and human accountability.',cta:'Review Standards',ctaHref:'/compliance',access:'public',status:'implemented',category:'Platform Foundation',capabilities:['Governed workflows','Multi-tenant controls','Evidence-driven operations','Human accountability'],integrations:['Policy engine','Audit trail','Reporting','Service operations'],workflow:['Define','Control','Execute','Verify','Improve'],triggers:['INTAKE_SUBMITTED'],apiEndpoints:['GET /api/platform/status']},
 {slug:'contact',title:'Contact Ross Tax Pro',eyebrow:'Company',subtitle:'Professional service with documented follow-through.',description:'Contact Ross Tax Pro Software Co. for enterprise software, professional tax operations, implementation, education, compliance, or partnership inquiries.',cta:'Email Our Team',ctaHref:'mailto:ceo@rosstaxsoftware.com',access:'public',status:'implemented',category:'Client Operations',capabilities:['Enterprise inquiries','Implementation planning','Professional support','Partnership intake'],integrations:['Email routing','Case assignment','Service tracking','Audit trail'],workflow:['Request','Authenticate as needed','Scope','Assign','Respond','Close'],triggers:['INTAKE_SUBMITTED'],apiEndpoints:['POST /api/v1/workflows/triggers']}
];

export const primaryNavigation=platformRoutes.filter(route=>['enterprise-experience','services','resources','compliance','documentation','contact'].includes(route.slug));
export const getRoute=(slug:string)=>platformRoutes.find(route=>route.slug===slug);
export const groupedRoutes=platformRoutes.reduce<Record<RouteCategory,PlatformRoute[]>>((groups,route)=>{groups[route.category].push(route);return groups;},{'Platform Foundation':[],'Client Operations':[],'Tax Operations':[],'Intelligence Fabric':[],'Governance':[],'Administration':[],'Education and Release':[]});
