export type PlatformRoute={slug:string;title:string;subtitle:string;description:string;cta:string;ctaHref:string;access:'public'|'authenticated'|'restricted'};
export const platformRoutes:PlatformRoute[]=[
{slug:'services',title:'Tax and Software Services',subtitle:'Secure operations from intake through resolution.',description:'Explore tax preparation, payroll, compliance, transcript operations, software solutions, and professional support.',cta:'Start Secure Intake',ctaHref:'/start',access:'public'},
{slug:'about',title:'Built for Accountable Tax Operations',subtitle:'Smarter Software. Stronger Results.',description:'Ross Tax Pro Software Co. combines practitioner workflows, controlled automation, auditability, and client service.',cta:'Review Our Standards',ctaHref:'/compliance',access:'public'},
{slug:'resources',title:'Professional Resource Center',subtitle:'Guides, workflows, notices, and operational references.',description:'Access educational material and approved public resources. Taxpayer records remain behind authenticated controls.',cta:'Browse Services',ctaHref:'/services',access:'public'},
{slug:'contact',title:'Contact Ross Tax Pro',subtitle:'Professional service with documented follow-through.',description:'Contact ceo@rosstaxsoftware.com for enterprise, software, tax-practice, or partnership inquiries.',cta:'Email Our Team',ctaHref:'mailto:ceo@rosstaxsoftware.com',access:'public'},
{slug:'start',title:'Start Secure Intake',subtitle:'Begin with identity, consent, and engagement verification.',description:'Production intake must connect to the authorized identity and document workflow before taxpayer information is collected.',cta:'Open Client Portal',ctaHref:'/portal',access:'public'},
{slug:'portal',title:'Client Portal',subtitle:'Documents, signatures, notices, and case status.',description:'Authenticated client access point. Production authentication is required before sensitive records are displayed.',cta:'Portal Sign In',ctaHref:'/api/platform/status',access:'authenticated'},
{slug:'ero',title:'ERO Workspace',subtitle:'Return pipeline, acknowledgments, rejects, and funding operations.',description:'Restricted workspace for authorized ERO personnel with MFA, RBAC, and complete audit logging.',cta:'Check Platform Status',ctaHref:'/api/platform/status',access:'restricted'},
{slug:'admin',title:'Administration Center',subtitle:'Tenants, users, credentials, policies, and system controls.',description:'Restricted administrative surface. Secrets are never rendered to browsers or committed to source control.',cta:'System Health',ctaHref:'/api/health',access:'restricted'},
{slug:'payroll',title:'Payroll Operations',subtitle:'Employees, earnings, deductions, filings, and statements.',description:'Controlled payroll workflows with approvals, reconciliation, reporting, and retention.',cta:'Review Services',ctaHref:'/services',access:'authenticated'},
{slug:'transcripts',title:'Transcript Center',subtitle:'Authorized request tracking and transcript intelligence.',description:'TDS and SOR features remain disabled until IRS authorization, certificates, endpoints, and production validation are recorded.',cta:'View Connection Status',ctaHref:'/api/platform/status',access:'restricted'},
{slug:'refunds',title:'Refund Intelligence',subtitle:'Funding, fee, exception, and case analytics.',description:'Combines verified IRS records and portal-assisted SBTPG imports without representing estimates as official determinations.',cta:'View Status',ctaHref:'/api/platform/status',access:'restricted'},
{slug:'compliance',title:'Security and Compliance',subtitle:'MFA, RBAC, encryption, WISP, logging, and retention.',description:'Controls are designed around least privilege, evidence preservation, approval gates, and incident response.',cta:'Contact Compliance',ctaHref:'mailto:ceo@rosstaxsoftware.com',access:'public'}
];
export const getRoute=(slug:string)=>platformRoutes.find(route=>route.slug===slug);
