import Link from 'next/link';
import {governanceRoles,permissions,rolePermissions} from '../../../lib/access-governance';

export const metadata={title:'RBAC Permissions Matrix',robots:{index:false,follow:false,noarchive:true}};

export default function RbacPage(){return <>
 <section className="page-hero"><div className="container"><nav className="breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href="/admin">Administration</Link><span>/</span><span>RBAC</span></nav><div className="page-hero__grid"><div><div className="eyebrow">Need to know · separation of duties · just in time</div><h1>RBAC Strict Roles and Permissions Matrix</h1><p className="lead">A code-backed permission registry for masterfile, transcript, e-file, client, notice, payment, reporting, credential, and administrative operations.</p></div><aside className="route-summary"><h2>Decision inputs</h2><dl><div><dt>Identity</dt><dd>Required</dd></div><div><dt>MFA</dt><dd>Required</dd></div><div><dt>Purpose</dt><dd>Required</dd></div><div><dt>Credential</dt><dd>Action dependent</dd></div><div><dt>Approval</dt><dd>Material actions</dd></div></dl></aside></div></div></section>
 <section className="notice-band"><div className="container"><strong>Enforcement rule:</strong> a green matrix cell alone is not sufficient. Runtime authorization also evaluates tenant, office, case scope, purpose, MFA, session risk, active credential status, and approval evidence.</div></section>
 <section className="section"><div className="container"><div style={{overflowX:'auto'}}><table style={{width:'100%',borderCollapse:'collapse',background:'#fff'}}><thead><tr><th style={{textAlign:'left',padding:'12px',border:'1px solid #d0d5dd'}}>Role</th>{permissions.map(permission=><th key={permission} style={{padding:'10px',border:'1px solid #d0d5dd',fontSize:11,minWidth:105}}>{permission.replaceAll('_',' ')}</th>)}</tr></thead><tbody>{governanceRoles.map(role=><tr key={role}><th style={{textAlign:'left',padding:'12px',border:'1px solid #d0d5dd'}}>{role.replaceAll('_',' ')}</th>{permissions.map(permission=>{const assigned=rolePermissions[role];const allowed=assigned[0]==='*'||(assigned as string[]).includes(permission);return <td key={permission} style={{textAlign:'center',padding:'10px',border:'1px solid #d0d5dd',fontWeight:900,color:allowed?'#137333':'#b42318'}}>{allowed?'✓':'—'}</td>})}</tr>)}</tbody></table></div></div></section>
 <section className="section section--dark"><div className="container lifecycle-grid"><div><div className="eyebrow">Privileged access lifecycle</div><h2>Request, approve, expire, and review.</h2><p>No permanent elevation is inferred from a job title. Privileged access should be time-bound, purpose-bound, independently approved, logged, and reviewed.</p></div><ol className="lifecycle"><li><span>1</span>Identity and MFA verified</li><li><span>2</span>Role and permission evaluated</li><li><span>3</span>Credential and purpose checked</li><li><span>4</span>Human approval recorded</li><li><span>5</span>Decision logged and access expires</li></ol></div></section>
 </>}
