import type {Metadata} from 'next';
import Link from 'next/link';
import RegistrationForm from '../../components/registration-form';

export const metadata:Metadata={title:'Enterprise Registration System',description:'Controlled registration and enrollment for taxpayers, practitioners, staff, providers, and tenant administrators.',robots:{index:false,follow:false,noarchive:true}};

export default function RegistrationPage(){return <>
 <section className="page-hero"><div className="container"><nav className="breadcrumbs"><Link href="/">Home</Link><span>/</span><span>Registration</span></nav><div className="page-hero__grid"><div><div className="eyebrow">Identity · Consent · Approval · Audit</div><h1>Enterprise Registration System</h1><p className="lead">A route-specific enrollment experience for clients, practitioners, staff, integration providers, and office administrators.</p><p>Registration creates a controlled application record. It does not automatically grant a role, activate an external adapter, or authorize transmission.</p></div><aside className="route-summary"><h2>Registration gates</h2><dl><div><dt>Email verification</dt><dd>Required</dd></div><div><dt>Identity verification</dt><dd>Required</dd></div><div><dt>Human approval</dt><dd>Required</dd></div><div><dt>Tenant assignment</dt><dd>Required</dd></div><div><dt>Audit trail</dt><dd>Immutable event</dd></div></dl></aside></div></div></section>
 <section className="notice-band"><div className="container"><strong>Fail-closed enrollment:</strong> submitting this form creates a pending registration. Access remains blocked until verification and approval complete.</div></section>
 <section className="section"><div className="container"><RegistrationForm/></div></section>
 <section className="section section--muted"><div className="container detail-grid"><article className="detail-card"><div className="eyebrow">Lifecycle</div><h2>Registration stages</h2><ol className="lifecycle"><li><span>1</span>Application submitted</li><li><span>2</span>Email and identity verification</li><li><span>3</span>Documents and authority review</li><li><span>4</span>Role and tenant approval</li><li><span>5</span>Activation and audit retention</li></ol></article><article className="detail-card"><div className="eyebrow">Separation of duties</div><h2>Approval boundaries</h2><ul className="check-list"><li>Applicants cannot approve their own privileged role</li><li>Provider enrollment requires contract and security evidence</li><li>External adapter activation requires separate owner approval</li><li>Suspension and revocation remain available after activation</li></ul></article></div></section>
 </>}
