import Link from 'next/link';
import {credentialTypes,governanceRoles,permissions,rolePermissions} from '../../../lib/access-governance';

export const dynamic='force-dynamic';
export const metadata={title:'Credential and RBAC Control Center',robots:{index:false,follow:false,noarchive:true}};

export default function CredentialDashboard(){return <>
 <section className="page-hero"><div className="container"><nav className="breadcrumbs"><Link href="/">Home</Link><span>/</span><Link href="/admin">Administration</Link><span>/</span><span>Credentials</span></nav><div className="page-hero__grid"><div><div className="eyebrow">Least privilege · MFA · evidence · review</div><h1>Credential and RBAC Control Center</h1><p className="lead">Govern professional credentials, role assignments, privileged approvals, periodic reviews, suspensions, and immutable access decisions.</p><div className="actions"><Link className="ross-btn ross-btn--gold" href="/register">Register workforce or provider</Link><Link className="ross-btn ross-btn--outline" href="/admin/rbac">Open RBAC matrix</Link></div></div><aside className="route-summary"><h2>Control posture</h2><dl><div><dt>Credential types</dt><dd>{credentialTypes.length}</dd></div><div><dt>Governed roles</dt><dd>{governanceRoles.length}</dd></div><div><dt>Permissions</dt><dd>{permissions.length}</dd></div><div><dt>Self approval</dt><dd>Prohibited</dd></div><div><dt>External authority</dt><dd>Not implied</dd></div></dl></aside></div></div></section>
 <section className="notice-band"><div className="container"><strong>Restricted identifiers:</strong> complete PTIN, EFIN, CAF, ERO, state e-file, and bank-product identifiers must remain encrypted. Public and ordinary operational views display masked values only.</div></section>
 <section className="section section--compact"><div className="container stat-grid" style={{marginTop:0}}><div className="stat-card"><strong>0</strong><span>Pending credential reviews</span></div><div className="stat-card"><strong>0</strong><span>Expiring credentials</span></div><div className="stat-card"><strong>0</strong><span>Temporary elevations</span></div><div className="stat-card"><strong>100%</strong><span>MFA required for privileged actions</span></div></div></section>
 <section className="section"><div className="container detail-grid"><article className="detail-card"><div className="eyebrow">Credential lifecycle</div><h2>Verification and status controls</h2><ol className="lifecycle"><li><span>1</span>Submit encrypted identifier and evidence</li><li><span>2</span>Independent document or authority review</li><li><span>3</span>Activate credential with reviewer identity</li><li><span>4</span>Assign role through separate approval</li><li><span>5</span>Review, suspend, expire, or revoke</li></ol></article><article className="detail-card"><div className="eyebrow">Enforced boundaries</div><h2>Mandatory governance rules</h2><ul className="check-list"><li>Manager approval before access</li><li>Quarterly privileged-access review</li><li>Immediate revocation for termination or material risk</li><li>AI personas cannot approve their own work</li><li>Credential evidence does not independently authorize external access</li><li>Every decision records purpose, scope, MFA, role, and outcome</li></ul></article></div></section>
 <section className="section section--muted"><div className="container"><div className="section-heading"><div><div className="eyebrow">Role registry</div><h2>Permissions are explicit—not inherited from titles</h2></div><p>The owner role may hold the complete internal permission set, but external-system operations still require active credentials, evidence gates, case scope, purpose, MFA, and human approval.</p></div><div className="route-grid">{governanceRoles.map(role=><article className="route-card" key={role}><h4>{role.replaceAll('_',' ')}</h4><p>{rolePermissions[role][0]==='*'?'Full internal platform permission set; external gates remain separate.':`${rolePermissions[role].length} assigned permissions.`}</p><ul>{rolePermissions[role][0]==='*'?<li>All internal permissions</li>:(rolePermissions[role] as string[]).slice(0,5).map(permission=><li key={permission}>{permission.replaceAll('_',' ')}</li>)}</ul><Link className="card-link" href="/admin/rbac">Inspect role matrix →</Link></article>)}</div></div></section>
 </>}
